### PR TITLE
added .rvmrc to .gitignore

### PR DESCRIPTION
**Pull request by rodrigues**
many people that cloned metric_fu should be using rvm, .rvmrc is kinda personal to be pushed to the project.

do you think the same? ;)

some discussion about this in another project: https://github.com/rails/rails/pull/194

### CODE REVIEW

**Comment by marksim** [comment]
I disagree.  Having .rvmrc is documentation for which Ruby this is typically run on.  There may be a few projects that need to have it ignored, but in general, check it in and leave off the gemsets... and/or auto create a very specific gemset if it doesn't exist.

**Comment by dmitryame** [comment]
+1 @marksim

**Comment by rodrigues** [comment]
I understand your opinion, however I would use a .rvmrc.example for doing this.

**Comment by lunks** [comment]
Currently metric_fu .rvmrc doesn't have a specific ruby version, just a gemset name.

**Comment by steveklabnik** [comment]
Tracking the .rvmrc is considered to be a best practice: https://rvm.beginrescueend.com/rvm/best-practices/

**Pull request closed without merging**
