### PR TITLE
Move chronic dependency to Gemfile

### PR DESCRIPTION
**Pull request by jnimety**
it looks like chronic is only used for development/testing, so remove gemspec dependency so it doesn't mess with downstream apps

Signed-off-by: Joel Nimety jnimety@continuity.net

### CODE REVIEW

**Comment by cgriego** [comment]
@jscruggs What's the status of this? I can't upgrade to newer versions of gems with fixes I need and keep metric_fu without this fix.

**Comment by ghost** [comment]
yep.. me too need to know the status of this and when will a stable version be out?

**Comment by crawlik** [comment]
Guys, please review and merge. tnx

**Comment by danmayer** [comment]
Part of the problem was churn was requiring to specific of a version of main and chronic. I relased 0.0.15 of churn which has 'looser' dependencies and should allow metric_fu to install 

Sorry about that.

**Comment by danmayer** [comment]
linking to my other comment, moving to a development_dependency would be great, but we should allow a less restrictive version.  like >= 0.3.0

https://github.com/jscruggs/metric_fu/issues/73

**Comment by emoreth** [comment]
Please merge...

**Comment by PragTob** [comment]
Please merge this, it looks like an awesome gem and I bet that many people listening to todays [Ruby Rogues podcast](http://rubyrogues.com/041-rr-code-metrics/) will want to try and check it out!

**Comment by danmayer** [comment]
So I made a number of changes to churn to try to fix the chronic depenancy issues, but the change needs to be made in metric_fu.

@rferraz made a fixed version 
gem install rferraz-metric_fu from  https://github.com/rferraz/metric_fu

I also pulled in nearly all the metric_fu pull requests which gets some nice fixes in and updated the churn requirement to make metric_fu work. It can be found https://github.com/danmayer/metric_fu

gem install danmayer-metric_fu

or Gemfile

group :development, :test do
  gem 'danmayer-metric_fu'
end

add to rake file: require 'metric_fu'

bundle exec rake metrics:all

Anyways, I will try to maintain this a little bit until @jscruggs has time to pull things in and make another mainline release.

**Comment by bf4** [comment]
Gem no longer maintained, See https://github.com/metricfu/metric_fu

**Pull request closed without merging**
