### PR TITLE
Fix deprecation warnings with ActiveSupport ~> 2.3.5

### PR DESCRIPTION
**Pull request by cgriego**
I've gotten tired of this message in my console. :)

```
DEPRECATION WARNING: require "activesupport" is deprecated and will be removed in Rails 3. Use require "active_support" instead. (called from /vendor/bundle/ruby/1.8/gems/activesupport-2.3.11/lib/activesupport.rb:2)
```

I chose this approach instead of a nested begin/rescue block so that people using versions before 2.3.5 didn't have to suffer the overhead of two exception backtraces being generated. I tested with the first and last patch versions of each minor version of ActiveSupport between 2.0.0 and 3.0.5

### CODE REVIEW

**Comment by marksim** [comment]
+1 On this pull request.

**Comment by marksim** [comment]
Any reason this hasn't been pulled in?

**Comment by steveklabnik** [comment]
+1. I submitted this as a pull request back in January, but it sat for months and wasn't pulled in, so don't expect anything to be done anytime soon.

**Comment by krainboltgreene** [comment]
Hoping to get more attention to this, as I've just started to use Metric Fu on a Rail3.1 project.

**Comment by christopher-john-czettel** [comment]
+1 on this one.

**Comment by bf4** [comment]
Gem no longer maintained, See https://github.com/metricfu/metric_fu

**Pull request closed without merging**
